#!/bin/bash

# Stop on errors and print all commands.
set -uex

# Tool directory.
DUNOVO="/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/src/dunovo"

###################
# Step 1: FastQC
###################
mkdir -p fastqc
##if (( $(ls -1 fastqc | wc -l) < 2 )); then
if [[ $# == 1  ]] && [[ $(ls -l fastqc | wc -l) < 2 ]] ; then
	echo "# Preparing fastqc reports."
	fastqc --outdir ./fastqc ${READS1}
	fastqc --outdir ./fastqc ${READS2} 
fi

########################################################
# Step 2: Du Novo - Make read families based on barcodes
########################################################
## (stating 'bash' is not required)
## example: make-families.sh reads_1.fastq reads_2.fastq > families.tsv
if [[ $# == 1 ]] && [[ ! -f "families.tsv" ]] ; then
	echo "# Preparing families.tsv file."
	$DUNOVO/make-families.sh ${READS1} ${READS2} > families.tsv
fi
if (( $( head families.tsv | wc -l | cut -d' ' -f1 ) == 0 )); then
        echo "### Families file is empty. The fastQ files could be empty. ###"
	exit 6
fi

#########################################################
# Step 3: Du Novo - Correct errors in barcodes (optional)
#########################################################
## example: 	baralign.sh families.tsv refdir barcodes.sam
##		correct.py families.tsv refdir/barcodes.fa barcodes.sam | sort > families.corrected.tsv
##if [[ ! -f "barcodes.sam" ]]; then
if [[ $# == 1 ]] && [[ ! -f "barcodes.sam" ]] ; then
	echo "# Preparing barcodes.sam file."
	$DUNOVO/baralign.sh families.tsv refdir barcodes.sam
fi
##if [[ ! -f "families.corrected.tsv" ]]; then
if [[ $# == 1 ]] && [[ ! -f "families.corrected.tsv" ]] ; then
	echo "# Preparing families.corrected.tsv file."
	$DUNOVO/correct.py families.tsv refdir/barcodes.fa barcodes.sam | sort > families.corrected.tsv
fi

################################################################
# Step 4: Du Novo - Multiple sequence alignment of read families
################################################################
# example: align-families.py families.tsv > families.msa.tsv
# The flag: -p auto | uses all available subprocesses.
##$DUNOVO/align-families.py -p auto families.corrected.tsv > families.corrected.msa.tsv

if [[ ! -f "families.corrected.tsv" ]]; then
	echo "### File 'families.corrected.tsv' does not exist for $SAMPLE_ID ###"
	exit 6
fi

# Test if split MSA files already exist.
if [[ ! -f "fam_corr_msa/fam.corr.msa.5.tsv"  ]]; then	
	echo "# Splitting MSA files and creating separate jobs for each."
	# Use Nick's awk solution to split files into chunks.
	mkdir -p fam_corr_msa
	awk -v nchunks=60 -v outbase=fam_corr_msa/fam.corr -f ../../../bin/chunk-families.awk families.corrected.tsv families.corrected.tsv 
	# Do a separate MSA for each split file.
	for FILE_DIR in $(ls --color=no fam_corr_msa/fam.corr.[0-9]*tsv); do \
		#$DUNOVO/align-families.py -p auto $FILE_DIR > $( echo $FILE_DIR | sed 's/\.corr\./.corr.msa./g' ) ; \
		sbatch ../../../bin/dunovo_msa.job ${SPECIES} ${SAMPLE_ID} ${FILE_DIR} ; \
	done
	exit 0
elif [[ -f "fam_corr_msa/fam.corr.msa.5.tsv"  ]]; then
	echo "# Joining split MSA files."
	# Join the split MSA files into one.
	cat fam_corr_msa/fam.corr.msa.[1-9]*.tsv > fam_corr_msa/fam.corr.msa.JOINED.tsv
fi

# Test if joined MSA file has content.
if (( $( head fam_corr_msa/fam.corr.msa.JOINED.tsv | wc -l | cut -d' ' -f1 ) == 0 )); then
        echo "### Families JOINED MSA file is empty. ###"
        exit 7
fi

##################################################################
# Step 5: Du Novo - Make consensus sequences from aligned families
##################################################################
# example: make-consensi.py --fastq-out 40 families.msa.tsv --dcs1 duplex_1.fq --dcs2 duplex_2.fq
#$DUNOVO/make-consensi.py --fastq-out 40 families.corrected.msa.tsv --dcs1 duplex_1.fq --dcs2 duplex_2.fq

echo "# Preparing DCS files." 

# With the MSA step done in split files, rejoined for this step.
cat fam_corr_msa/fam.corr.msa.[1-9]*.tsv > fam_corr_msa/fam.corr.msa.JOINED.tsv
$DUNOVO/make-consensi.py --fastq-out 40 fam_corr_msa/fam.corr.msa.JOINED.tsv --dcs1 duplex_1.fq --dcs2 duplex_2.fq

################################################################################################
# Step 6: PNAS paper - Trim 12bp from 5' to account for end-repair step from library preparation
################################################################################################

echo "# Trimming 5' end in fastq files (with Barbara's suggestions.)."

trimmomatic PE -phred64 \
	duplex_1.fq duplex_2.fq \
	duplex_1.trim.fq duplex_1un.trim.fq \
	duplex_2.trim.fq duplex_2un.trim.fq \
	HEADCROP:12

##############################################################################################
# Step 7: Du Novo - Post-procesing (trim consensus reads with high-density of ambiguous bases)
##############################################################################################
# example: trimmer.py --acgt --window 10 --thres 0.3 --min-length 50 duplex_1.fa duplex_2.fa duplex.filt_1.fa duplex.filt_2.fa
#$DUNOVO/bfx/trimmer.py --acgt --window 10 --thres 0.3 --min-length 50 duplex_1.fq duplex_2.fq duplex.filt_1.fq duplex.filt_2.fq

echo "# Trimming reads with DuNovo suggestions."

$DUNOVO/bfx/trimmer.py --acgt --window 10 --thres 0.3 --min-length 50 duplex_1.trim.fq duplex_2.trim.fq duplex.filt_1.fq duplex.filt_2.fq




