#!/bin/bash

## Stop on errors and print all commands.
set -uex


#######
# Tools:
########
BAMUTIL=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/src/bamUtil/bin/bam
GATK=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/src/gatk-4.2.5.0/gatk


##############
## References:
##############
# Rhesus macaque (relinearized using `seqkit restart`).
# Mouse genome (includes a fixed insertion of A present in this pedigree).

# Picks the reference based on the project ID.
if [ ${SAMPLE_ID} == 'SRR16770886' ]
then
	echo "# This sample (SRR16770886) was contaminated with mouse DNA other than the main macaque."
	echo "# Using a combined fasta with both Mouse and Rhesus macaque references (rheMac10/NC_005089insA)."
	# Just the chrM reference for macaque (rheMac10) and mouse (NC_005089_9821insA).
	REF=.../data/refs/contaminated_mac_mou/rheMac10_NC_005089_9821insA.chrM.fa
	REFrelin=.../data/refs/contaminated_mac_mou/rheMac10_NC_005089_9821insA.chrM_relin8400.fa

elif [ ${SPECIES} == 'macaque' ] ; then 
	echo "# Using Rhesus macaque references (rheMac10)."
	# Just the chrM reference for rheMac10.
	REF=data/refs/rhesus_macaque/rheMac10.chrM.fa
	REFrelin=data/refs/rhesus_macaque/rheMac10.chrM_relin8400.fa	

elif [ ${SPECIES} == 'mouse' ] ; then
	echo "# Using mouse references (NC_005089insA)."
	# Just the chrM reference for mouse (NC_005089_9821insA).
	REF=data/refs/mouse/NC_005089_9821insA.chrM.fa
	REFrelin=data/refs/mouse/NC_005089_9821insA.chrM_relin8400.fa

elif [ $SPECIES == 'human' ] ; then
	echo "# Using human reference (NC_012920.1)"
	# Human mtDNA ref (excludes position 3107, an N in the reference due to historical mistakes).
	REF=data/refs/human/NC_012920.1.with_chrM_del3107.fa
	REFrelin=data/refs/human/NC_012920.1.with_chrM_del3107_relin8400.fa

else
	echo "# Cannot recognize which reference to use."
	exit 3
fi


##################
## Work directory:
##################
# Create a new merged SRR directory.
DIR_SUFFIX=`echo ${SAMPLE_ID_1} | rev | cut -d'_' --complement -f1 | rev`
mkdir -p ${DIR_SUFFIX}_merged ; cd ${DIR_SUFFIX}_merged

# File names: Duplex consensus reads (paired end).
R1='duplex.filt_1.fq'
R2='duplex.filt_2.fq'

# Print working directory.
pwd



############################################################
#   1. Concatenate the multiple SRR runs for this sample   #
############################################################
# Create a merged fastQ.
if [ -f "../$SRR_3/duplex.filt_1.fq" ]; then
	echo "### ../$SRR_3/duplex.filt_1.fq exists."
	echo "### Adding ${SRR_1}, ${SRR_2}, and ${SRR_3} fastQ files into one."
	# Paired end files 1.
	cat ../${SRR_1}/duplex.filt_1.fq ../${SRR_2}/duplex.filt_1.fq ../${SRR_3}/duplex.filt_1.fq > duplex.filt_1.fq
	# Paired end files 2.
	cat ../${SRR_1}/duplex.filt_2.fq ../${SRR_2}/duplex.filt_2.fq ../${SRR_3}/duplex.filt_2.fq > duplex.filt_2.fq
elif [ -f "../$SRR_2/duplex.filt_1.fq" ]; then
	echo "### ../$SRR_2/duplex.filt_1.fq exists."
	echo "### Adding ${SRR_1} and ${SRR_2} fastQ files into one."
        # Paired end files 1.
        cat ../${SRR_1}/duplex.filt_1.fq ../${SRR_2}/duplex.filt_1.fq > duplex.filt_1.fq
        # Paired end files 2.
        cat ../${SRR_1}/duplex.filt_2.fq ../${SRR_2}/duplex.filt_2.fq > duplex.filt_2.fq
else
	echo "### Merged fastQ files could not be created. ###"
	exit 8
fi



###############################################################
#   2. Map duplex consensus reads to reference with bwa-mem   #
###############################################################
# Create a BAM file and sort it (-t nThreads).
### (Du Novo suggestion: GATK LeftAlignIndels | Alternative: freebayes' bamleftalign)
### The same indel can often be placed at multiple positions and still represent the same haplotype.
#bwa mem $REF $R1 $R2 | samtools sort > alignments.bam

# Left-align indels from read data. 
## The WellformedReadFilter default setting breaks if the read lengths are not consistent (which we trim) and if there is an N in the read.
$GATK LeftAlignIndels -R $REF -I alignments.bam -O alignments.bla.bam --disable-read-filter WellformedReadFilter

# Filter for chrM.
samtools view alignments.bla.bam chrM > alignments.bla.chrM.bam

# Clip overlapping read pairs.
$BAMUTIL clipOverlap --in alignments.bla.chrM.bam --stats --out alignments.clipped.bam

# Index the BAM file.
samtools index alignments.clipped.bam

# Exclude multi-mapped reads (keep uniquely-mapped reads).
samtools view alignments.clipped.bam | grep -v "XA:" | samtools view -bS -T $REF - > alignments.umr.bam

# Keep the unmapped reads.
samtools view -f4 alignments.umr.bam > alignments.umr.unmapped



###############################################################
#   3. Map duplex consensus reads to RELINEARIZED reference   #
###############################################################
# Create a BAM file and sort it (-t nThreads).
### (Du Novo suggestion: GATK LeftAlignIndels | Alternative: freebayes' bamleftalign)
### The same indel can often be placed at multiple positions and still represent the same haplotype.
#bwa mem $REFrelin $R1 $R2 | samtools sort > relin.alignments.bam

# Left-align indels from read data.
## The WellformedReadFilter default setting breaks if the read lengths are not consistent (which we trim) and if there is an N in the read.
$GATK LeftAlignIndels -R $REFrelin -I relin.alignments.bam -O relin.alignments.bla.bam --disable-read-filter WellformedReadFilter

# Exclude multi-mapped reads (keep uniquely-mapped reads).
samtools view relin.alignments.bla.bam | grep -v "XA:" | samtools view -bS -T $REF - > relin.alignments.umr.bam

# Index the BAM file.
samtools index relin.alignments.umr.bam

# Filter for chrM.
samtools view relin.alignments.umr.bam chrM > relin.alignments.umr.chrM.bam

# Clip overlapping read pairs.
samtools view relin.alignments.umr.chrM.bam | $BAMUTIL clipOverlap --in - --stats --out relin.alignments.clipped.bam

# Index the BAM file.
samtools index relin.alignments.clipped.bam

# Keep the unmapped reads.
samtools view -f4 relin.alignments.clipped.bam > relin.alignments.clipped.unmapped


