#!/bin/bash

## Stop on errors and print all commands.
set -uex


########
# Tools:
########
NVC=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/src/nvc/nvc
GATK=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/src/gatk-4.2.5.0/gatk


##############
## References:
##############
# Rhesus macaque (relinearized using `seqkit restart`).
# Mouse genome (includes a fixed insertion of A present in this pedigree).

# Picks the reference based on the project ID.
if [ ${SAMPLE_ID} == 'SRR16770886' ]
then
	echo "# This sample (SRR16770886) was contaminated with mouse DNA other than the main macaque."
	echo "# Using a combined fasta with both Mouse and Rhesus macaque references (rheMac10/NC_005089insA)."
	# Just the chrM reference for macaque (rheMac10) and mouse (NC_005089_9821insA).
	REF=.../data/refs/contaminated_mac_mou/rheMac10_NC_005089_9821insA.chrM.fa
	REFrelin=.../data/refs/contaminated_mac_mou/rheMac10_NC_005089_9821insA.chrM_relin8400.fa

elif [ ${SPECIES} == 'macaque' ] ; then 
	echo "# Using Rhesus macaque references (rheMac10)."
	# Just the chrM reference for rheMac10.
	REF=data/refs/rhesus_macaque/rheMac10.chrM.fa
	REFrelin=data/refs/rhesus_macaque/rheMac10.chrM_relin8400.fa	

elif [ ${SPECIES} == 'mouse' ] ; then
	echo "# Using mouse references (NC_005089insA)."
	# Just the chrM reference for mouse (NC_005089_9821insA).
	REF=data/refs/mouse/NC_005089_9821insA.chrM.fa
	REFrelin=data/refs/mouse/NC_005089_9821insA.chrM_relin8400.fa

elif [ $SPECIES == 'human' ] ; then
	echo "# Using human reference (NC_012920.1)"
	# Human mtDNA ref (excludes position 3107, an N in the reference due to historical mistakes).
	REF=data/refs/human/NC_012920.1.with_chrM_del3107.fa
	REFrelin=data/refs/human/NC_012920.1.with_chrM_del3107_relin8400.fa

else
	echo "# Cannot recognize which reference to use."
	exit 3
fi



#################################
#	Variant calling		#
#################################

# Naive Variant Caller.
echo "# Variant calling with NVC."
python2 $NVC/naive_variant_caller.py \
        -r $REF --region=chrM --use_strand --min_base_quality=0 --min_mapping_quality=20 --ploidy=1 \
        -b alignments.clipped.bam -o variants.${SAMPLE_ID}.vcf


################################################
#       Variant calling (RELINEARIZED)         #
################################################

# Naive Variant Caller.
echo "# Variant calling with NVC."
python2 $NVC/naive_variant_caller.py \
        -r $REFrelin --region=chrM --use_strand --min_base_quality=0 --min_mapping_quality=20 --ploidy=1 \
        -b relin.alignments.clipped.bam -o relin.variants.${SAMPLE_ID}.vcf



echo "Job ended"; date "+%Y-%m-%d.%H:%M:%S"


