#!/bin/bash

## Stop on errors and print all commands.
set -uex


########
# Tools:
########
BCFTOOLS=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/src/bcftools/bcftools


##############
## References:
##############
# Rhesus macaque (relinearized using `seqkit restart`).
# Mouse genome (includes a fixed insertion of A present in this pedigree).

# Picks the reference based on the project ID.
if [ ${SAMPLE_ID} == 'SRR16770886' ]
then
	echo "# This sample (SRR16770886) was contaminated with mouse DNA other than the main macaque."
	echo "# Using a combined fasta with both Mouse and Rhesus macaque references (rheMac10/NC_005089insA)."
	# Just the chrM reference for macaque (rheMac10) and mouse (NC_005089_9821insA).
	REF=.../data/refs/contaminated_mac_mou/rheMac10_NC_005089_9821insA.chrM.fa
	REFrelin=.../data/refs/contaminated_mac_mou/rheMac10_NC_005089_9821insA.chrM_relin8400.fa

elif [ ${SPECIES} == 'macaque' ] ; then 
	echo "# Using Rhesus macaque references (rheMac10)."
	# Just the chrM reference for rheMac10.
	REF=data/refs/rhesus_macaque/rheMac10.chrM.fa
	REFrelin=data/refs/rhesus_macaque/rheMac10.chrM_relin8400.fa	

elif [ ${SPECIES} == 'mouse' ] ; then
	echo "# Using mouse references (NC_005089insA)."
	# Just the chrM reference for mouse (NC_005089_9821insA).
	REF=data/refs/mouse/NC_005089_9821insA.chrM.fa
	REFrelin=data/refs/mouse/NC_005089_9821insA.chrM_relin8400.fa

elif [ $SPECIES == 'human' ] ; then
	echo "# Using human reference (NC_012920.1)"
	# Human mtDNA ref (excludes position 3107, an N in the reference due to historical mistakes).
	REF=data/refs/human/NC_012920.1.with_chrM_del3107.fa
	REFrelin=data/refs/human/NC_012920.1.with_chrM_del3107_relin8400.fa

else
	echo "# Cannot recognize which reference to use."
	exit 3
fi



#################################
#	Variant filtering	#
#################################

# Filter for indel variants.
echo "# Filtering for indels."

# Prepare new VCF header.
cat variants.${SAMPLE_ID}.vcf | grep '##' > header.txt
if [ ${SPECIES} == 'macaque' ] ; then
        echo "##contig=<ID=chrM,length=16564>" >> header.txt
elif [ ${SPECIES} == 'mouse' ] ; then
        echo "##contig=<ID=chrM,length=16300>" >> header.txt
elif [ ${SPECIES} == 'human' ] ; then
        echo "##contig=<ID=chrM,length=16569>" >> header.txt
else
	exit 99
fi
cat variants.${SAMPLE_ID}.vcf | grep '#CHROM' >> header.txt

# Prepare sample name into a file.
echo $SAMPLE_ID > sample.txt

# Add SRR ID to variants header.
$BCFTOOLS reheader --samples sample.txt --header header.txt variants.${SAMPLE_ID}.vcf > variants.id.${SAMPLE_ID}.vcf

# Filter for just indels.
#$BCFTOOLS view -v indels variants.id.${SAMPLE_ID}.vcf > indels.${SAMPLE_ID}.vcf
## Split multiallelic sites, then filter for just indel variants.
$BCFTOOLS reheader --samples sample.txt --header header.txt variants.${SAMPLE_ID}.vcf | $BCFTOOLS norm -m - | $BCFTOOLS view -v indels > indels.${SAMPLE_ID}.vcf

# Filter for just substitutions.
$BCFTOOLS reheader --samples sample.txt --header header.txt variants.${SAMPLE_ID}.vcf | $BCFTOOLS norm -m - | $BCFTOOLS view --exclude-types indels --exclude 'ALT="N"' > subst.${SAMPLE_ID}.vcf


################################################
#       Variant filtering (RELINEARIZED)       #
################################################

# Filter for indel variants.
echo "# Filtering for indels in relin alignment."

# Prepare new VCF header.
cat relin.variants.${SAMPLE_ID}.vcf | grep '##' > header.txt
if [ ${SPECIES} == 'macaque' ] ; then
	echo "##contig=<ID=chrM,length=16564>" >> header.txt
elif [ ${SPECIES} == 'mouse' ] ; then
	echo "##contig=<ID=chrM,length=16300>" >> header.txt
elif [ ${SPECIES} == 'human' ] ; then
	echo "##contig=<ID=chrM,length=16569>" >> header.txt
else
	exit 99
fi
cat relin.variants.${SAMPLE_ID}.vcf | grep '#CHROM' >> header.txt

# Prepare sample name into a file.
echo $SAMPLE_ID > sample.txt

# Add SRR ID to variants header.
$BCFTOOLS reheader --samples sample.txt --header header.txt relin.variants.${SAMPLE_ID}.vcf > relin.variants.id.${SAMPLE_ID}.vcf

# Add chrM contig info to header.
#$BCFTOOLS view -v indels relin.variants.id.${SAMPLE_ID}.vcf > relin.indels.${SAMPLE_ID}.vcf
# Split multiallelic sites, then filter for just indel variants, and rejoin multiallelic sites.
$BCFTOOLS reheader --samples sample.txt  --header header.txt relin.variants.id.${SAMPLE_ID}.vcf | $BCFTOOLS norm -m - | $BCFTOOLS view -v indels > relin.indels.${SAMPLE_ID}.vcf

# Filter for just substitutions.
$BCFTOOLS reheader --samples sample.txt  --header header.txt relin.variants.id.${SAMPLE_ID}.vcf | $BCFTOOLS norm -m - | $BCFTOOLS view --exclude-types indels --exclude 'ALT="N"' > relin.subst.${SAMPLE_ID}.vcf




