#!/bin/bash
#SBATCH --job-name=varFilt
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=30000
#SBATCH --time=0-80:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=ejt89@psu.edu
#SBATCH --chdir=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/bin
#SBATCH --output=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/bin/log/ejt89-varFilt%j.out
#SBATCH --error=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/bin/log/ejt89-varFilt%j.err

echo "Job started"; date "+%Y-%m-%d.%H:%M:%S"

# Standard tmp folder is too small.
TMPDIR=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/tmp

# Conda environment.
export CONDA_ENVS_PATH=/galaxy/home/ejt89/.conda/envs
#source /opt/anaconda/etc/profile.d/conda.sh
source /galaxy/home/ejt89/anaconda3/etc/profile.d/conda.sh
##conda activate /galaxy/home/ejt89/.conda/envs/bioinfo
source activate /galaxy/home/ejt89/.conda/envs/bioinfo
##conda activate bioinfo
conda info --envs
conda list

## Stop on errors and print all commands.
set -uex

################
## Code testing.
################
if [[ $# -ne 2 ]] ; then
    echo '### You need to provide two arguments: SPECIES , SRR_ID/Sample_ID ###'
    echo '### e.g. macaque SRR16770761 ###'
    echo '### You provided '$#' argument(s). ###'
    exit 1
fi

if [[ $2 = [Sh][Rs][R0-9]* ]] ; then
        echo "### The second argument starts with SRR or hs (for human samples) ###"

elif [[ $2 = *_merged ]]; then
        echo "### The second argument matches the format for a sample with multiple SRR runs. ###"
        echo "### Pipeline will continue on this alignment from merged SRR runs. ###"   
else
        echo "### The second argument does NOT start with SRR (or hs for human samples), or match the format for a sample with multiple seq runs ('_merged'). ###"
        exit 2
fi

# Assign the arguments.
SPECIES=$1 #Species name (macaque or mouse)
##SAMPLE_ID=$( echo $2 | rev | cut -d'/' -f1 | rev )  #SRR_ID (e.g. SRR16770761) or Sample_ID for humans (e.g. hs003_Oo4)
SAMPLE_ID=$2  #SRR_ID (e.g. SRR16770761) or Sample_ID for humans (e.g. hs003_Oo4)

# File names: Duplex consensus reads (paired end).
R1='duplex.filt_1.fq'
R2='duplex.filt_2.fq'


##################
## Work directory
#################
cd ../results

# Project ID (species_SRAproject).
cd ${SPECIES}*/${SAMPLE_ID}

# Print working directory.
pwd

########
# Tools:
########
NVC=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/src/nvc/nvc
GATK=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/src/gatk-4.2.5.0/gatk
BCFTOOLS=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/src/bcftools/bcftools
SURVIVOR=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/src/SURVIVOR/Debug/SURVIVOR


##############
## References:
##############
# Rhesus macaque (relinearized using `seqkit restart`).
# Mouse genome (includes a fixed insertion of A present in this pedigree).

# Picks the reference based on the project ID.
if [ ${SAMPLE_ID} == 'SRR16770886' ]
then
	echo "# This sample (SRR16770886) was contaminated with mouse DNA other than the main macaque."
	echo "# Using a combined fasta with both Mouse and Rhesus macaque references (rheMac10/NC_005089insA)."
	# Just the chrM reference for macaque (rheMac10) and mouse (NC_005089_9821insA).
	REF=.../data/refs/contaminated_mac_mou/rheMac10_NC_005089_9821insA.chrM.fa
	REFrelin=.../data/refs/contaminated_mac_mou/rheMac10_NC_005089_9821insA.chrM_relin8400.fa

elif [ ${SPECIES} == 'macaque' ] ; then 
	echo "# Using Rhesus macaque references (rheMac10)."
	# Just the chrM reference for rheMac10.
	#REF=data/refs/rhesus_macaque/rheMac10.chrM.fa
	#REFrelin=data/refs/rhesus_macaque/rheMac10.chrM_relin8400.fa	

elif [ ${SPECIES} == 'mouse' ] ; then
	echo "# Using mouse references (NC_005089insA)."
	# Just the chrM reference for mouse (NC_005089_9821insA).
	#REF=data/refs/mouse/NC_005089_9821insA.chrM.fa
	#REFrelin=data/refs/mouse/NC_005089_9821insA.chrM_relin8400.fa

elif [ $SPECIES == 'human' ] ; then
	echo "# Using human reference (NC_012920.1)"
	# Human mtDNA ref (excludes position 3107, an N in the reference due to historical mistakes).
	REF=data/refs/human/NC_012920.1.with_chrM_del3107.fa
	REFrelin=data/refs/human/NC_012920.1.with_chrM_del3107_relin8400.fa

else
	echo "# Cannot recognize which reference to use."
	exit 3
fi




#################################
#	Variant filtering	#
#################################

# Filter for indel variants.
echo "# Filtering for indels."

# Prepare new VCF header.
cat variants.${SAMPLE_ID}.vcf | grep '##' > header.txt
if [ ${SPECIES} == 'macaque' ] ; then
        echo "##contig=<ID=chrM,length=16564>" >> header.txt
elif [ ${SPECIES} == 'mouse' ] ; then
        echo "##contig=<ID=chrM,length=16300>" >> header.txt
elif [ ${SPECIES} == 'human' ] ; then
        echo "##contig=<ID=chrM,length=16569>" >> header.txt
else
	exit 99
fi
cat variants.${SAMPLE_ID}.vcf | grep '#CHROM' >> header.txt

# Prepare sample name into a file.
echo $SAMPLE_ID > sample.txt

# Add SRR ID to variants header.
$BCFTOOLS reheader --samples sample.txt --header header.txt variants.${SAMPLE_ID}.vcf > variants.id.${SAMPLE_ID}.vcf

# Filter for just indels.
#$BCFTOOLS view -v indels variants.id.${SAMPLE_ID}.vcf > indels.${SAMPLE_ID}.vcf
## Split multiallelic sites, then filter for just indel variants.
$BCFTOOLS reheader --samples sample.txt --header header.txt variants.${SAMPLE_ID}.vcf | $BCFTOOLS norm -m - | $BCFTOOLS view -v indels > indels.${SAMPLE_ID}.vcf

# Filter for just substitutions.
$BCFTOOLS reheader --samples sample.txt --header header.txt variants.${SAMPLE_ID}.vcf | $BCFTOOLS norm -m - | $BCFTOOLS view --exclude-types indels --exclude 'ALT="N"' > subst.${SAMPLE_ID}.vcf


################################################
#       Variant filtering (RELINEARIZED)       #
################################################

# Filter for indel variants.
echo "# Filtering for indels in relin alignment."

# Prepare new VCF header.
cat relin.variants.${SAMPLE_ID}.vcf | grep '##' > header.txt
if [ ${SPECIES} == 'macaque' ] ; then
	echo "##contig=<ID=chrM,length=16564>" >> header.txt
elif [ ${SPECIES} == 'mouse' ] ; then
	echo "##contig=<ID=chrM,length=16300>" >> header.txt
elif [ ${SPECIES} == 'human' ] ; then
	echo "##contig=<ID=chrM,length=16569>" >> header.txt
else
	exit 99
fi
cat relin.variants.${SAMPLE_ID}.vcf | grep '#CHROM' >> header.txt

# Prepare sample name into a file.
echo $SAMPLE_ID > sample.txt

# Add SRR ID to variants header.
$BCFTOOLS reheader --samples sample.txt --header header.txt relin.variants.${SAMPLE_ID}.vcf > relin.variants.id.${SAMPLE_ID}.vcf

# Add chrM contig info to header.
#$BCFTOOLS view -v indels relin.variants.id.${SAMPLE_ID}.vcf > relin.indels.${SAMPLE_ID}.vcf
# Split multiallelic sites, then filter for just indel variants, and rejoin multiallelic sites.
$BCFTOOLS reheader --samples sample.txt  --header header.txt relin.variants.id.${SAMPLE_ID}.vcf | $BCFTOOLS norm -m - | $BCFTOOLS view -v indels > relin.indels.${SAMPLE_ID}.vcf

# Filter for just substitutions.
$BCFTOOLS reheader --samples sample.txt  --header header.txt relin.variants.id.${SAMPLE_ID}.vcf | $BCFTOOLS norm -m - | $BCFTOOLS view --exclude-types indels --exclude 'ALT="N"' > relin.subst.${SAMPLE_ID}.vcf



echo "Job ended"; date "+%Y-%m-%d.%H:%M:%S"


