#!/bin/bash

# Stop on errors and print all commands.

#################
#  Parameters	#
#################

# Assign the arguments.
SPECIES=$1 #Species name (macaque, mouse, or human)
GENOME='chrM'

# Mt genome size based on species.
	if [ ${SPECIES} = 'macaque' ] ; then
		GENOME_SIZE='16564'

	elif [ ${SPECIES} = 'mouse' ] ; then
		GENOME_SIZE='16300'

	elif [  ${SPECIES} = 'human' ] ; then
		GENOME_SIZE='16569'

	else
		#echo "### Species (${SPECIES}) not recognized."
		exit 2
	fi


#########################################################
#  Estimate mean mapped read depth for each sample 	#
#########################################################

### Start a for loop to iterate over all directories of SRRs (including merged ones, even though their fastQs are repeated).
for ID in $( ls --color=no | grep '[GRSh][0-9hRs][R0-9]'  ); do \
#for ID in $(ls --color=no | grep 'SRR' | grep -A200 SRR16770974); do 
	
	cd ${ID}
	
	if [[ ! -f alignments.${GENOME}.clipped.bam  ]] ; then
		###echo "${ID} does NOT have alignments.chrM.clipped.bam"	
		cd ..
                continue
	fi
	# If it has an alignment, produce an mpileup file for this SRR.
	if [[ ! -f alignments.${GENOME}.clipped.mpileup  ]] ; then
                samtools mpileup alignments.chrM.clipped.bam > alignments.chrM.clipped.mpileup
        fi

	# Get number of reads mapped by position.
	#samtools mpileup alignments.${GENOME}.clipped.bam > alignments.${GENOME}.clipped.mpileup
	###echo "${ID} produced alignments.chrM.clipped.mpileup"

	# Skips sample if the mpileup is empty.
	if (( $(wc -l alignments.${GENOME}.clipped.mpileup | cut -f1 -d' ') == 0 )) ; then
		cd ..
		continue
	fi

	## Keep just mtDNA (chrM) from alignment mpileup.
	grep 'chrM' alignments.${GENOME}.clipped.mpileup > alignments.${GENOME}.clipped.chrM.mpileup		
	###echo "${ID} kept chrM in alignments.clipped.chrM.mpileup"

	# Skips sample if the chrM mpileup is empty.
	#if (( $(wc -l alignments.clipped.chrM.mpileup | cut -f1 -d' ') == 0 )) ; then
	#	cd ..
	#	continue
	#fi

	# Get the sum of reads per position.
###	SUM_READS=$(cat alignments.clipped.mpileup | grep 'chrM' | cut -f4 | awk '{s+=$1} END {print s}')
###	SUM_READS=$(cat alignments.clipped.mpileup | cut -f4 | awk '{s+=$1} END {print s}')
	SUM_READS=$(cat alignments.${GENOME}.clipped.chrM.mpileup | cut -f4 | awk '{s+=$1} END {print s}')

	# Only keep if mean read depth is above 1.
	if [[ $(expr ${SUM_READS} / ${GENOME_SIZE}) != 0 ]]; then
		# Divide sum of reads by position over size of Mt genome.
		MEAN_DEPTH=$(expr ${SUM_READS} / ${GENOME_SIZE})
		# Add to output file.
		echo "${ID}	${MEAN_DEPTH}	${SUM_READS}"
	fi
	
	cd ..

# End the for loop with results for all SRR directories.
###done > meanReadDepths_chrM_${SPECIES}.txt
###done > meanReadDepths_${SPECIES}.txt
done > meanReadDepths.${GENOME}.${SPECIES}.txt

