#!/bin/bash
#SBATCH --job-name=meanReadDepth
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=10000
#SBATCH --time=0-80:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=ejt89@psu.edu
#SBATCH --chdir=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/bin
#SBATCH --output=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/bin/log/ejt89-meanR%j.out
#SBATCH --error=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/bin/log/ejt89-meanR%j.err
#SBATCH --exclude nn[6-8]

echo "Job started"; date "+%Y-%m-%d.%H:%M:%S"

# Conda environment.
export CONDA_ENVS_PATH=/galaxy/home/ejt89/.conda/envs
#source /opt/anaconda/etc/profile.d/conda.sh
source /galaxy/home/ejt89/anaconda3/etc/profile.d/conda.sh
##conda activate /galaxy/home/ejt89/.conda/envs/bioinfo
source activate /galaxy/home/ejt89/.conda/envs/bioinfo
##conda activate bioinfo
conda info --envs
conda list

# Standard tmp folder is too small.
TMPDIR=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/tmp

# Stop on errors and print all commands.
set -uex

################
## Code testing.
################
if [[ $# -ne 1 ]] ; then
    echo '### You need to provide one argument: SPECIES ###'
    echo '### e.g. macaque ###'
    echo '### You provided '$#' argument(s). ###'
    exit 1
fi

# Assign the arguments.
SPECIES=$1 #Species name (macaque, mouse, or human)
GENOME='nuDNA' #'chrM' or 'nuDNA'

# Mt genome size based on species.
	if [ ${SPECIES} = 'macaque' ] ; then
		GENOME_SIZE='16564'

	elif [ ${SPECIES} = 'mouse' ] ; then
		GENOME_SIZE='16300'

	elif [  ${SPECIES} = 'human' ] ; then
		GENOME_SIZE='16569'

	else
		#echo "### Species (${SPECIES}) not recognized."
		exit 2
	fi

################
# Work directory
################
cd ../results

# Project ID (species_SRAproject)
cd ${SPECIES}*


#########################################################
#  Estimate mean mapped read depth for each sample 	#
#########################################################

### Start a for loop to iterate over all directories of SRRs (including merged ones, even though their fastQs are repeated).
for ID in $( ls --color=no | grep '[GRSh][0-9hRs][R0-9]'  ); do \
#for ID in $(ls --color=no | grep 'SRR' | grep -A200 SRR16770974); do 
	
	cd ${ID}
	
	if [[ ! -f alignments.${GENOME}.clipped.bam  ]] ; then
		###echo "${ID} does NOT have alignments.chrM.clipped.bam"	
		cd ..
                continue
	fi
	# If it has an alignment, produce an mpileup file for this SRR.
	if [[ ! -f alignments.${GENOME}.clipped.mpileup  ]] ; then
                samtools mpileup alignments.chrM.clipped.bam > alignments.chrM.clipped.mpileup
        fi

	# Get number of reads mapped by position.
	#samtools mpileup alignments.${GENOME}.clipped.bam > alignments.${GENOME}.clipped.mpileup
	###echo "${ID} produced alignments.chrM.clipped.mpileup"

	# Skips sample if the mpileup is empty.
	if (( $(wc -l alignments.${GENOME}.clipped.mpileup | cut -f1 -d' ') == 0 )) ; then
		cd ..
		continue
	fi

	## Keep just mtDNA (chrM) from alignment mpileup.
	grep 'chrM' alignments.${GENOME}.clipped.mpileup > alignments.${GENOME}.clipped.chrM.mpileup		
	###echo "${ID} kept chrM in alignments.clipped.chrM.mpileup"

	# Skips sample if the chrM mpileup is empty.
	#if (( $(wc -l alignments.clipped.chrM.mpileup | cut -f1 -d' ') == 0 )) ; then
	#	cd ..
	#	continue
	#fi

	# Get the sum of reads per position.
###	SUM_READS=$(cat alignments.clipped.mpileup | grep 'chrM' | cut -f4 | awk '{s+=$1} END {print s}')
###	SUM_READS=$(cat alignments.clipped.mpileup | cut -f4 | awk '{s+=$1} END {print s}')
	SUM_READS=$(cat alignments.${GENOME}.clipped.chrM.mpileup | cut -f4 | awk '{s+=$1} END {print s}')

	# Only keep if mean read depth is above 1.
	if [[ $(expr ${SUM_READS} / ${GENOME_SIZE}) != 0 ]]; then
		# Divide sum of reads by position over size of Mt genome.
		MEAN_DEPTH=$(expr ${SUM_READS} / ${GENOME_SIZE})
		# Add to output file.
		echo "${ID}	${MEAN_DEPTH}	${SUM_READS}"
	fi
	
	cd ..

# End the for loop with results for all SRR directories.
###done > meanReadDepths_chrM_${SPECIES}.txt
###done > meanReadDepths_${SPECIES}.txt
done > meanReadDepths.${GENOME}.${SPECIES}.txt


echo "Job ended"; date "+%Y-%m-%d.%H:%M:%S"