#!/bin/bash

# Stop on errors and print all commands.
set -uex


# Assign the arguments.
SPECIES=$1 #Species name (macaque, mouse, or human)
echo $SPECIES


################
# Work directory
################
cd ../results/${SPECIES}_*
mkdir -p indels
mkdir -p relin_indels
mkdir -p subst
mkdir -p relin_subst

mkdir -p mod_indels
mkdir -p mod_relin_indels
mkdir -p mod_subst
mkdir -p mod_relin_subst


#########################################################
#  Merge all variant VCFs using a python script 	#
#########################################################

# Make a copy of indel VCFs to a new directory.
cp [Sh][Rs][R0-9]*/indels.[Sh][Rs][R0-9]*.vcf indels/
cp [Sh][Rs][R0-9]*/relin.indels.[Sh][Rs][R0-9]*.vcf relin_indels/
cp [Sh][Rs][R0-9]*/subst.[Sh][Rs][R0-9]*.vcf subst/
cp [Sh][Rs][R0-9]*/relin.subst.[Sh][Rs][R0-9]*.vcf relin_subst/


if [[ $SPECIES == "macaque" ]] ; then
        cp Rh*_merged/indels.Rh*.vcf indels/
        cp Rh*_merged/relin.indels.Rh*.vcf relin_indels/
        cp Rh*_merged/subst.Rh*.vcf subst/
        cp Rh*_merged/relin.subst.Rh*.vcf relin_subst/
elif [[ $SPECIES == "mouse" ]] ; then
        cp G*_merged/indels.G*.vcf indels/
        cp G*_merged/relin.indels.G*.vcf relin_indels/
        cp G*_merged/subst.G*.vcf subst/
        cp G*_merged/relin.subst.G*.vcf relin_subst/
#elif [[ $SPECIES == "human" ]] ; then
#       cp hs[0-9]*_merged/indels.hs[0-9]*.vcf indels
#       cp hs[0-9]*_merged/relin.indels.hs[0-9]*.vcf relin_indels/
fi

# Modify the INFO column of VCFs.
bash utils/modifyINFO.sh indels
bash utils/modifyINFO.sh relin_indels
bash utils/modifyINFO.sh subst
bash utils/modifyINFO.sh relin_subst

# Script that merges VCFs into one multiVCF (using bcftools merge).
bash utils/multisamp_vcf.sh indels
bash utils/multisamp_vcf.sh relin_indels
bash utils/multisamp_vcf.sh mod_indels
bash utils/multisamp_vcf.sh mod_relin_indels

bash utils/multisamp_vcf.sh subst
bash utils/multisamp_vcf.sh relin_subst
bash utils/multisamp_vcf.sh mod_subst
bash utils/multisamp_vcf.sh mod_relin_subst



