#!/bin/bash
#SBATCH --job-name=mergeVCFs
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=50000
#SBATCH --cpus-per-task=8
#SBATCH --time=0-80:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=ejt89@psu.edu
#SBATCH --chdir=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/bin
#SBATCH --output=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/bin/log/ejt89-mergeVCF%j.out
#SBATCH --error=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/bin/log/ejt89-mergeVCF%j.err
#SBATCH --exclude nn[6-8]

echo "Job started"; date "+%Y-%m-%d.%H:%M:%S"

# Conda environment.
export CONDA_ENVS_PATH=/galaxy/home/ejt89/.conda/envs
#source /opt/anaconda/etc/profile.d/conda.sh
source /galaxy/home/ejt89/anaconda3/etc/profile.d/conda.sh
##conda activate /galaxy/home/ejt89/.conda/envs/bioinfo
source activate /galaxy/home/ejt89/.conda/envs/bioinfo
##conda activate bioinfo
conda info --envs
conda list

# Standard tmp folder is too small.
TMPDIR=/nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/tmp

# Stop on errors and print all commands.
set -uex

################
## Code testing.
################
if [[ $# -ne 1 ]] ; then
    echo '### You need to provide one argument: SPECIES ###'
    echo '### e.g. macaque ###'
    echo '### You provided '$#' argument(s). ###'
    exit 1
elif [[ $1 != "macaque" && $1 != "mouse" && $1 != "human" ]] ; then
    echo '### The argument should either be macaque, mouse, or human ###'
    exit 2
fi

# Assign the arguments.
SPECIES=$1 #Species name (macaque, mouse, or human)
echo $SPECIES

################
# Work directory
################
cd ../results/${SPECIES}_*
mkdir -p indels
mkdir -p relin_indels
mkdir -p subst
mkdir -p relin_subst

mkdir -p mod_indels
mkdir -p mod_relin_indels
mkdir -p mod_subst
mkdir -p mod_relin_subst

#########################################################
#  Merge all variant VCFs using a python script 	#
#########################################################

# Make a copy of indel VCFs to a new directory.
cp [Sh][Rs][R0-9]*/indels.[Sh][Rs][R0-9]*.vcf indels/
cp [Sh][Rs][R0-9]*/relin.indels.[Sh][Rs][R0-9]*.vcf relin_indels/
cp [Sh][Rs][R0-9]*/subst.[Sh][Rs][R0-9]*.vcf subst/
cp [Sh][Rs][R0-9]*/relin.subst.[Sh][Rs][R0-9]*.vcf relin_subst/


if [[ $SPECIES == "macaque" ]] ; then
        cp Rh*_merged/indels.Rh*.vcf indels/
        cp Rh*_merged/relin.indels.Rh*.vcf relin_indels/
        cp Rh*_merged/subst.Rh*.vcf subst/
        cp Rh*_merged/relin.subst.Rh*.vcf relin_subst/
elif [[ $SPECIES == "mouse" ]] ; then
        cp G*_merged/indels.G*.vcf indels/
        cp G*_merged/relin.indels.G*.vcf relin_indels/
        cp G*_merged/subst.G*.vcf subst/
        cp G*_merged/relin.subst.G*.vcf relin_subst/
#elif [[ $SPECIES == "human" ]] ; then
#       cp hs[0-9]*_merged/indels.hs[0-9]*.vcf indels
#       cp hs[0-9]*_merged/relin.indels.hs[0-9]*.vcf relin_indels/
fi

# Modify the INFO column of VCFs.
bash ../../bin/modifyINFO.sh indels
bash ../../bin/modifyINFO.sh relin_indels
bash ../../bin/modifyINFO.sh subst
bash ../../bin/modifyINFO.sh relin_subst

# Script that merges VCFs into one multiVCF (using bcftools merge).
bash ../../bin/multisamp_vcf.sh indels
bash ../../bin/multisamp_vcf.sh relin_indels
bash ../../bin/multisamp_vcf.sh mod_indels
bash ../../bin/multisamp_vcf.sh mod_relin_indels

bash ../../bin/multisamp_vcf.sh subst
bash ../../bin/multisamp_vcf.sh relin_subst
bash ../../bin/multisamp_vcf.sh mod_subst
bash ../../bin/multisamp_vcf.sh mod_relin_subst



################
### Alternative. 
#ls /nfs/brubeck.bx.psu.edu/scratch4/edmundo/duplexSeq/results/${SPECIES}*/*/variants.id.* > sample_files.txt
#python mergeVCFs.py




echo "Job ended"; date "+%Y-%m-%d.%H:%M:%S"



